name: "capstone_23692"
version: "1.0.0"
config-version: 2

profile: "default"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"


# ============================================================
# MODEL CONFIGURATION
# ============================================================

models:

  capstone_23692:

    # --------------------------------------------------------
    # BRONZE / STAGING
    # --------------------------------------------------------

    staging:

      bronze:
        +schema: "{{ env_var('DBT_BRONZE_SCHEMA') }}"


    # --------------------------------------------------------
    # SILVER
    # --------------------------------------------------------

    silver:
      +schema: "{{ env_var('DBT_SILVER_SCHEMA') }}"


    # --------------------------------------------------------
    # GOLD
    # --------------------------------------------------------

    gold:
      +schema: "{{ env_var('DBT_GOLD_SCHEMA') }}"


  # ----------------------------------------------------------
  # ELEMENTARY
  # ----------------------------------------------------------

  elementary:
    +schema: elementary